[package]
name = "dataportal"
version = "0.0.0"
authors = ["Keiji Yoshida <kjmrknsn@gmail.com>"]
description = "Data Portal"
license = "MIT/Apache-2.0"

[dependencies]

[[bin]]
name = "dataportal-api"
path = "src/bin/api.rs"
